### ISSUE TITLE
Error on pins show view 

### ISSUE THREAD

**Issue by oliviervanhees** [oliviervanhees/friends4food#91]
I have removed the "set external url" method on the pin model, so we can manually change the image url  by hand. However, now all the pins show view receive an error. When we modify the record, the error is gone. Seems like we need to mass update all the records?

https://github.com/oliviervanhees/friends4food/commit/6fe9c8d1ef95e9b0626e1ade590bbcd4d5cafbbc

**Comment by timvdalen** [comment]
Issue here seems to be your `phone_number_link` helper, which assumes that all records have a non-nil telephone number.
